#!/bin/bash
#
# Log file cleaning script
#
# This script deletes typical old log files,
# logrotate files, and similar log backups.
#
# Please be certain you don't need
# these log files before you run this.
#
# Syntax:
#
#     log-file-cleaning [path]
#
# Example:
#
#     log-file-cleaning /var/log
#
# The path default is `/var/log` which is typical on popular Unix systems.
#
#
# ## Custom `rm` command
#
# You can customize the command by providing your own `rm` command
# as an environment variable.
#
# Example:
#
#     rm="/bin/rm -f" log-file-cleaning
#
#
# ## Specifics
#
# This removes many kinds of log files.
#
# File names that end with:
#
#   * .bz, .gz, .tar, etc.
#
#   * .bak, .old, .tmp, etc.
#
#
# File names that match:
#
#   * log.[0-9]*
#
#   * [0-9]*.log
#
# File names that match:
#
#   * btmp.[0-9]*
#
#   * dmesg.[0-9]*
#
#   * mail.err.[0-9]*
#
#   * syslog.[0-9]*
#
#   * wtmp.[0-9]*
#
#   * xferlog.[0-9]*
#
# Any `atop` files - warning - this will delete the current file too;
# this is a known issue of this script, and is on the roadmap to fix.
#
#   * atop/atop_[0-9]*
#
#
# ## Implementation notes
#
# This script aims to work even when a disk is full or commands are missing.
# For example, this scripts starts by deleting files one name by one name,
# rather than relying on more-sophisticated file globbing or using `find`.
#
# This script source code aims to be descriptive and meaningful,
# so a systems administrator can easily comment out lines as needed,
# or add new lines easily without affecting any other lines.
#
# If you are a developer who is creating a patch or pull request,
# please keep this code pattern, rather than trying to introduce
# features such as more globbing, loops, non-POSIX commands, etc.
#
#
# ## Tracking
#
# Command: log-file-cleaning
# Version: 4.0.0
# Created: 2012-12-09
# Updated: 2019-09-09
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
##
set -u

path=${1:-/var/log}
rm=${rm:-rm -f}

##
#
# Remove top level files because this reclaims space immediately
#
##

## Remove compressed files

$rm $path/*.bz
$rm $path/*.bz2
$rm $path/*.bzip
$rm $path/*.gz
$rm $path/*.tar
$rm $path/*.zip
$rm $path/*.7zip

## Remove sidelined files

$rm $path/*.bak
$rm $path/*.back
$rm $path/*.backup
$rm $path/*.old
$rm $path/*.tmp
$rm $path/*.temp
$rm $path/*.temporary

## Remove numbered files of generic file names

$rm $path/*.log.[0-9]*
$rm $path/*.log.[0-9]*.gz
$rm $path/*.[0-9].log
$rm $path/*.[0-9].log.gz

## Remove numbeed files of specific applications

$rm $path/alternatives.log.[0-9]*
$rm $path/apt/history.log.[0-9]*.gz
$rm $path/btmp.[0-9]*
$rm $path/dmesg.[0-9]*
$rm $path/dpkg.log.[0-9]*
$rm $path/kern.log.[0-9]*
$rm $path/mail.err.[0-9]*
$rm $path/syslog.[0-9]*
$rm $path/wtmp.[0-9]*
$rm $path/xferlog.[0-9]*


# Remove all atop log files.
# TODO: preserve the most recent atop file.
$rm $path/atop/atop_[0-9]*

# Remove all Mac OSX Apple System Log files.
# TODO: scope this so it keeps the most recent one.
$rm $path/asl/*.asl
$rm $path/DiagnosticMessages/*.asl

## Remove anything else by using our related script
rm-rotated-files "$path"
